// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID    pgtype.UUID
	Src   string
	Label string
}
